jobs:
  build:
    docker:
      - image: rdelfin/rust_ci:1.67.0
    steps:
      - checkout
      - run: cargo build
      - run: cargo test
      - run: node clippy -- -D clippy::cargo -D clippy::all -D warnings
